local ItemDatabase = {
	["RiceSprout"] = {
		ItemName = "ต้นกล้าข้าว",
		Icon = "rbxassetid://108601657790274",
		Description = "ต้นกล้่าของต้นข้าว สำหรับนำไปดำนา"
	},
	["RiceSprout(quest)"] = {
		ItemName = "ต้นกล้าข้าว",
		Icon = "rbxassetid://108601657790274",
		Description = "ต้นกล้่าของต้นข้าว สำหรับนำไปดำนา"
	},
	["Sickle"] = {
		ItemName = "เคียวเกี่ยวข้าว",
		Icon = "rbxassetid://112599052775939",
		Description = "ใช้เก็บเกี่ยวข้าวที่พร้อมเก็บเกี่ยว"
	},
	["HarvestedRice"] = {
		ItemName = "ข้าว",
		Icon = "rbxassetid://108635479285971",
		Description = "ผลผลิตทืี่ได้จากการเกี่ยวข้าว สามารถนำไปนวดที่ลานนวดข้าว เพื่อแปรรูปเป็นข้าวเปลือก"
	},
	["Lantern"] = {
		ItemName = "ตะเกียง",
		Icon = "rbxassetid://97994209898857",
		Description = "ให้แสงสว่างในตอนกลางคืน"
	},

	["SlingShot"] = {
		ItemName = "หนังสติ๊ก",
		Icon = "rbxassetid://110895871320534",
		Description = "ใช้ไล่สัตว์"
	},

	["TraditionalFabric"] = {
		ItemName = "ผ้าก่วย",
		Icon = "rbxassetid://86228350521413",
		Description = "ใช้แปรรูปเป็นผลิตภัณฑ์ต่างๆเพื่อเพิ่มมูลค่า"
	}

}

return ItemDatabase