local ItemDatabase = {
	["RiceSprout"] = {
		ItemName = "ต้นกล้าข้าว",
		Icon = "rbxassetid://108601657790274",
		Description = "ต้นกล้่าของต้นข้าว สำหรับนำไปดำนา"
	},
	["RiceSprout(quest)"] = {
		ItemName = "ต้นกล้าข้าว",
		Icon = "rbxassetid://108601657790274",
		Description = "ต้นกล้่าของต้นข้าว สำหรับนำไปดำนา"
	},
	["Sickle"] = {
		ItemName = "เคียวเกี่ยวข้าว",
		Icon = "rbxassetid://112599052775939",
		Description = "ใช้เก็บเกี่ยวข้าวที่พร้อมเก็บเกี่ยว"
	},
	["HarvestedRice"] = {
		ItemName = "ข้าว",
		Icon = "rbxassetid://108635479285971",
		Description = "ผลผลิตทืี่ได้จากการเกี่ยวข้าว สามารถนำไปนวดที่ลานนวดข้าว เพื่อแปรรูปเป็นข้าวเปลือก"
	},
	
	["Lantern"] = {
		ItemName = "ตะเกียง",
		Icon = "rbxassetid://123456789",
		Description = "ให้แสงสว่างในตอนกลางคืน"
	}
}

return ItemDatabase